title: "Casa Farms"
description: "Modular Food Production and Solar Power Plant Development"
about: "Modular Food Production and Solar Power Plant Development"
location: "Iowa City, Iowa, USA"
email: bryan@pratherhuff.com
baseurl: "/farms.casa/"

url: "https://bryandph.github.io" # replace by your site's url
twitter_username: "pratherhuff"
github_username:  "bryandph"
author: "Bryan Prather-Huff"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - cap

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - cap

# exclude files
exclude:
  - LICENSE
  - README.md
